# application-dev.yml
# Server配置
server:
  address:
    - 127.0.0.1
    - monkey-dev.mng.developer.yhm.cn
  port: 8443
# Spring配置
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/db_monkey?useUnicode=true&characterEncoding=UTF8&serverTimezone=UTC&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
    hikari:
      # 连接池名称
      pool-name: HikariCP-Pool
      # 最小空闲连接数量
      minimum-idle: 5
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 空闲连接存活最大时间，默认600000毫秒（10分钟）
      idle-timeout: 600000
      # 连接的最长生命周期，值0表示无限生命周期，默认1800000毫秒即30分钟
      max-lifetime: 1800000
      # 默认自动提交行为,默认值：true
      auto-commit: true
      # 数据库连接超时时间,默认30秒，即30000毫秒
      connection-timeout: 30000
    type: com.zaxxer.hikari.HikariDataSource
# MyBatis配置
mybatis-plus:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-field: deleted
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0